// MCP2515_SPI INSTRUCTION SET
#define RESET 0xC0
#define READ  0x03
#define WRITE 0x02
#define READ_STATUS 0xA0
#define RX_STATUS 0xB0
#define BIT_MODIFY 0x05
#define CANSTAT    0xE
#define CANCTRL    0xF

#define READRX_RXB0SIDH 0x90
#define READRX_RXB0D0   0x92
#define READRX_RXB1SIDH 0x94
#define READRX_RXB1D0   0x96
#define RX_STATUS 0xB0

// Message Request-To-Send
#define RTS_TXB0 0x81
#define RTS_TXB1 0x82
#define RTS_TXB2 0x84

// Load TX Buffer
#define SPI_TXB0SIDH  0x40  //TX buffer 0, Start at TXB0SIDH
#define SPI_TXB0D0    0x41  //TX buffer 0, Start at TXB0D0
#define SPI_TXB1SIDH  0x42  //TX buffer 1, Start at TXB1SIDH
#define SPI_TXB1D0    0x43  //TX buffer 1, Start at TXB1D0
#define SPI_TXB2SIDH  0x44  //TX buffer 2, Start at TXB0SIDH
#define SPI_TXB2D0    0x45  //TX buffer 2, Start at TXB2D0

///////////////////////////////////////////////////////////////////////////
//  READ RX BUFFER INSTRUCTION
#define SPI_RXB0SIDH  0x90  //RX buffer 0, Start at RXB0SIDH
#define SPI_RXB0D0    0x92  //RX buffer 0, Start at RXB0D0
#define SPI_RXB1SIDH  0x94  //RX buffer 1, Start at RXB1SIDH
#define SPI_RXB1D0    0x96  //RX buffer 1, Start at RXB1D0

// Transmit Buffer TXB0
#define TXB0CTRL   0x30  //TXBnCTRL – TRANSMIT BUFFER n CONTROL REGISTER
#define TXRTSCTRL  0x0D  //TXRTSCTRL – TXnRTS PIN CONTROL AND STATUS REGISTER
#define TXB0SIDH   0x31  //TXBnSIDH – TRANSMIT BUFFER n STANDARD IDENTIFIER HIGH
#define TXB0SIDL   0x32  //TXBnSIDL – TRANSMIT BUFFER n STANDARD IDENTIFIER LOW
#define TXB0EID8   0x33  //TXBnEID8 – TRANSMIT BUFFER n EXTENDED IDENTIFIER HIGH
#define TXB0EID0   0x34  //TXBnEID8 – TRANSMIT BUFFER n EXTENDED IDENTIFIER HIGH
#define TXB0DLC    0x35  //TXBnDLC - TRANSMIT BUFFER n DATA LENGTH CODE
#define TXB0Dm     0x36  //TXBnDm – TRANSMIT BUFFER n DATA BYTE m


// Transmit Buffer TXB1
#define TXB1CTRL   0x40  //TXBnCTRL – TRANSMIT BUFFER n CONTROL REGISTER
#define TXB1SIDH   0x41  //TXBnSIDH – TRANSMIT BUFFER n STANDARD IDENTIFIER HIGH
#define TXB1SIDL   0x42  //TXBnSIDL – TRANSMIT BUFFER n STANDARD IDENTIFIER LOW
#define TXB1EID8   0x43  //TXBnEID8 – TRANSMIT BUFFER n EXTENDED IDENTIFIER HIGH
#define TXB1EID0   0x44  //TXBnEID8 – TRANSMIT BUFFER n EXTENDED IDENTIFIER HIGH
#define TXB1DLC    0x45  //TXBnDLC - TRANSMIT BUFFER n DATA LENGTH CODE


// Transmit Buffer TXB2
#define TXB2CTRL   0x50  //TXBnCTRL – TRANSMIT BUFFER n CONTROL REGISTER
#define TXB2SIDH   0x51  //TXBnSIDH – TRANSMIT BUFFER n STANDARD IDENTIFIER HIGH
#define TXB2SIDL   0x52  //TXBnSIDL – TRANSMIT BUFFER n STANDARD IDENTIFIER LOW
#define TXB2EID8   0x53  //TXBnEID8 – TRANSMIT BUFFER n EXTENDED IDENTIFIER HIGH
#define TXB2EID0   0x54  //TXBnEID8 – TRANSMIT BUFFER n EXTENDED IDENTIFIER HIGH
#define TXB2DLC    0x55  //TXBnDLC - TRANSMIT BUFFER n DATA LENGTH CODE

///////////////////////////////////////////////////////////////////////////

// Receive Message Buffering
#define RXB0CTRL  0x60   //RXB0CTRL – RECEIVE BUFFER 0 CONTROL
#define RXB1CTRL  0x70   //RXB1CTRL – RECEIVE BUFFER 0 CONTROL
#define RXB2CTRL  0x80   //RXB2CTRL – RECEIVE BUFFER 0 CONTROL
#define BFPCTRL   0x0C   //BFPCTRL – RXnBF PIN CONTROL AND STATUS
#define RXB0SIDH  0x61   //RXB0SIDH – RECEIVE BUFFER n STANDARD IDENTIFIER HIGH
#define RXB1SIDH  0x71   //RXB1SIDH – RECEIVE BUFFER n STANDARD IDENTIFIER HIGH
#define RXB0SIDL  0x62   //RXB0SIDL – RECEIVE BUFFER n STANDARD IDENTIFIER LOW
#define RXB1SIDL  0x72   //RXB1SIDL – RECEIVE BUFFER n STANDARD IDENTIFIER LOW
#define RXB0EID8  0x63   //RXBnEID8 – RECEIVE BUFFER n EXTENDED IDENTIFIER HIGH
#define RXB1EID8  0x73   //RXBnEID8 – RECEIVE BUFFER n EXTENDED IDENTIFIER HIGH
#define RXB0EID0  0x64   //RXBnEID0 – RECEIVE BUFFER n EXTENDED IDENTIFIER LOW
#define RXB1EID0  0x74   //RXBnEID0 – RECEIVE BUFFER n EXTENDED IDENTIFIER LOW
#define RXB0DLC   0x65   //RXBnDLC – RECEIVE BUFFER n DATA LENGHT CODE
#define RXB1DLC   0x75   //RXB1DLC – RECEIVE BUFFER n DATA LENGHT CODE
#define RXB0DM    0x66   //RXB0DM – RECEIVE BUFFER n DATA BYTE M
#define RXB1DM    0x6D   //RXB1DM – RECEIVE BUFFER n DATA BYTE M
#define RXB2DM    0x76   //RXB2DM – RECEIVE BUFFER n DATA BYTE M
#define RXB3DM    0x7D   //RXB3DM – RECEIVE BUFFER n DATA BYTE M
// TXBnDm – TRANSMIT BUFFER n DATA BYTE m1
#define TXB0D0     0x36  //TXBnDm – TRANS1MIT BUFFER n DATA BYTE m
#define TXB1D1     0x3D  //TXBnDm – TRANS1MIT BUFFER n DATA BYTE m
#define TXB2D2     0x46  //TXBnDm – TRANS1MIT BUFFER n DATA BYTE m
#define TXB3D3     0x4D  //TXBnDm – TRANS1MIT BUFFER n DATA BYTE m
#define TXB4D4     0x56  //TXBnDm – TRANS1MIT BUFFER n DATA BYTE m
#define TXB5D5     0x5D  //TXBnDm – TRANS1MIT BUFFER n DATA BYTE m



///////////////////////
#define CNF1 0x2A        //CNF1 – CONFIGURATION 1 (ADDRESS: 2Ah)
#define CNF2 0x29        //CNF2 – CONFIGURATION 1 (ADDRESS: 2Ah)
#define CNF3 0x28        //CNF3 – CONFIGURATION 1 (ADDRESS: 2Ah)

#define RXF0SIDH 0x00
#define RXM0SIDH 0x20


// RX Filter registers HIGH and LOW
#define  RXF0SIDH 0x00
#define  RXF0SIDL 0x01

#define  RXF1SIDH 0x04
#define  RXF1SIDL 0x05

#define  RXF2SIDH 0x08
#define  RXF2SIDL 0x09

#define  RXF3SIDH 0x10
#define  RXF3SIDL 0x11

#define  RXF4SIDH 0x14
#define  RXF4SIDL 0x15

#define  RXF5SIDH 0x18
#define  RXF5SIDL 0x19
////////////////////////

//  MASK n STANDARD IDENTIFIER HIGH and LOW
#define RXM0SIDH 0x20
#define RXM0SIDL 0x21

#define RXM1SIDH 0x24
#define RXM1SIDL 0x25
/////////////////////////////////////
